### ISSUE TITLE
Bug report: Add-on don't work due to Create 0.5.1 update

### ISSUE THREAD

**Issue by ClashofCraft972** [Lgmrszd/CreateMountedStorages#6]
### Describe your issue

Hi :)

 
Create resently made a new update which has made add-ons not functional.
Will you update this mod to the last Create update ?

I'm currently making a 1.18.2 modpack for me and my friends. And this mod would be cool to have.

 

Good Afternoon

### Mod version

1.18.2

### Forge version

40.2.4

### Create version

0.5.1

**Comment by tema3210** [comment]
```-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-1.0.8.jar:?] {}
-- MOD moremountedstorages --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/simibubi/create/AllTileEntities
		at com.juh9870.moremountedstorages.integrations.create.CreativeCrateRegistry.affectedStorages(CreativeCrateRegistry.java:28) ~[moremountedstorages-1.2.2.jar%2374!/:1.2.2] {re:classloading}
		at com.juh9870.moremountedstorages.ContraptionStorageRegistry.initCache(ContraptionStorageRegistry.java:43) ~[moremountedstorages-1.2.2.jar%2374!/:1.2.2] {re:classloading}
		at com.juh9870.moremountedstorages.MoreMountedStorages.commonSetup(MoreMountedStorages.java:59) ~[moremountedstorages-1.2.2.jar%2374!/:1.2.2] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_181_MoreMountedStorages_commonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.9.jar%2387!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.9.jar%2386!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

Here we go;

likely, that registry got moved to a https://github.com/Creators-of-Create/Create/blob/mc1.18/0.5.1/src/main/java/com/simibubi/create/AllBlockEntityTypes.java
